### ISSUE TITLE
Реализация апгрейдов

### ISSUE THREAD

**Issue by grihabor** [grihabor/garbage-clicker#107]
# Хранение абстрактного апгрейда

Каждый апгрейд по сути инкрементит на 1 некоторую величину, которая хранится в базе.

Для каждого апгрейда необходимо хранить (помимо того, что должен иметь shop item):

- ключ величины, которую нужно инкрементить

## Пример

При покупке апгрейда "дешевые автоматы" должна увеличиться величина "automata_cost_reduction" на единицу. От этой величины в свою очередь должна зависеть цена автомата:

`automata_cost = base_cost * (k ^ automata_count) * (q ^ automata_cost_reduction)`, 
где `k > 1`, 
а `q < 1`, 
поэтому `k ^ automata_count` тем больше, чем больше `automata_count`,
а `q ^ automata_cost_reduction` тем меньше, чем больше `automata_cost_reduction`

# ВАЖНО

В этом таске должно быть реализовано только хранение информации о произвольном улучшении. Реализация конкретных улучшений должна быть после #112 в таске #113.

**Comment by RedSnail** [comment]
@grihabor у нас уже есть count'ы улучшений, которые лежат в sPref, не лучше будет просто рассчитывать всё, исходя втч из cout'ов улучшений?

**Comment by SomeAnonimCoder** [comment]
готово
