### ISSUE TITLE
Проверка, является ли stream api причиной вылета программы

### ISSUE THREAD

**Issue by DansingWithWolfs** [grihabor/garbage-clicker#119]
Нужно попробовать воспользоваться какой-нибудь старой версией, созданной до того, как мы начали использовать stream api.

**Comment by DansingWithWolfs** [comment]
Является.

**Comment by grihabor** [comment]
Погоди, проблема же не решена

**Comment by grihabor** [comment]
Зачем закрывать?

**Comment by grihabor** [comment]
Сюда пиши все версии, необходимые, какие у тебя, из несоответствие

**Comment by DansingWithWolfs** [comment]
Моя версия андроида 6.0.1, ошибку пишет ```Failed to find byte code for java/util/function/Supplier```

**Comment by RedSnail** [comment]
да, является. #125 
я заменил использование stream api на retrostream (и они не везде синонимичны)
