### ISSUE TITLE
Баг с переполнением int - отрицательное количество денег

### ISSUE THREAD

**Issue by SomeAnonimCoder** [grihabor/garbage-clicker#155]
Из-за переполнения int'ов цены и число денег становятся отрицательными. Возможно, решится сменой типа на Long

**Comment by grihabor** [comment]
Нет. Так делать не надо

**Comment by SomeAnonimCoder** [comment]
Тогда как? BigInteger не засунется в SharedPreferences

**Comment by grihabor** [comment]
Это связано с #152

**Comment by grihabor** [comment]
нужно хранить лишь необходимую часть

**Comment by RedSnail** [comment]
#174
