### ISSUE TITLE
Список улучшений в UpgradeShopFragment

### ISSUE THREAD

**Issue by grihabor** [grihabor/garbage-clicker#20]
Простейший список улучшений

Делать после #16

**Comment by DansingWithWolfs** [comment]
список улучшений - ListView.
В onClick прописываем создание 5 элементов классов, наследующихся от класса Upgrade: UpgradeClick;
UpgradeTimeOfAutomat;
UpgradePerformanceOfAutomat;
UpgradeCostOfUpgrade;
UpgradeCostOfAuromat.
В listView 5 кликабельных элементов.  Заполняется или картинкой, или строкой (посмотрим потом).
Каждая картинка или строка берётся из объекта соответствующего класса.

**Comment by grihabor** [comment]
Поменяли названия

**Comment by DansingWithWolfs** [comment]
Новые названия:
UpgradeManualClick ;
AutomataDelayReduce;
AutomataCostReduce;
UpgradeCostReduce;
AutomataPerfomanceUpgrade;
