### ISSUE TITLE
Отдельный поток для автоматов

### ISSUE THREAD

**Issue by grihabor** [grihabor/garbage-clicker#22]
Автоматы умеют перерабатывать мусор в материалы пассивно. Чтобы это реализовать, предлагаю использовать отдельный поток, в котором будет производится увеличение счетчика материалов.

Чтобы затем отобразить эти изменения, нужно одно из двух:
- либо мучаться с колбэками
- либо использовать RxJava

Вариант с RxJava лучше во всех отношениях, однако нужно с ней разбираться. У нас нет столько времени, так что будем юзать колбэки

Передачу сообщений из фрагмента покупки автоматов предлагаю использовать ConcurrentLinkedQueue или подобную потокобезопасную очередь

Делать после #15

**Comment by AfanasiyLeonov** [comment]
Гриша, а нам не будет ли проще из класса автомата сразу слать изменения в SharedPreferences? Это избавит от коллбэков, да и так тупо проще

**Comment by grihabor** [comment]
Ок, но аккуратнее https://stackoverflow.com/questions/4693387/sharedpreferences-and-thread-safety
