### ISSUE TITLE
Create abstract class AbstractAutomate

### ISSUE THREAD

**Issue by AfanasiyLeonov** [grihabor/garbage-clicker#48]
Создать класс, от которого будем наследовать все автоматы. Он имеет две public переменные: int time и int quality - соответственно время и количество перерабатываемых ресурсов.

**Comment by grihabor** [comment]
Давай назовем Automata

**Comment by grihabor** [comment]
И мы договорились, что там будет ещё количество автоматов

**Comment by grihabor** [comment]
И договорились, что и время, и эффективность будет float

**Comment by grihabor** [comment]
Решили, что сразу делаем shopitem
