### ISSUE TITLE
Создание базального коммита

### ISSUE THREAD

**Issue by RedSnail** [grihabor/garbage-clicker#6]
Эта задача неделима и, как решил совет кодеров в столовке, её делает Артём.
Нужно создать коммит, где будет воплощена идеология игры, его будут пулить остальные и добавлять фичи. 
Идеология -- есть завод, на него кликает пользователь, получает сибурики, и экологию, есть 2 кнопки: качать за экологию (идейно: агитировать народ, чтобы они несли мусор и вы получали больше денег), качать за сибурики (идейно, модернизировать заводы для улучшения экологии)
От базального коммита не требуется никакой анимации, сбалансированных цен и доходов. Любая прокачка просто будет увеличивать количество доходов (не в той валюте, за которую вы этот апгрейт купили) с клика на 15% и следующая будет стоить на 30% дороже предыдущей. При клике на завод мы изначально получаем одинаковое количество сибуриков и экологии.

**Comment by grihabor** [comment]
Стоп, почему тогда просто не сделать первый экран в xml и все? Без логики, чтобы еще быстрее начать всем

**Comment by RedSnail** [comment]
И если реализация фич будет иметь общего предка с реализованной главной
идеей, мёрж не будет таким болезненным

27 февр. 2018 г. 12:12 ПП пользователь oleg.demianchenko@gmail.com написал:

Все в работе так или иначе эту стадию пройдут: наличие главной идеи и
отсутствие фич

27 февр. 2018 г. 11:16 ДП пользователь "Gregory" <notifications@github.com>
написал:

Стоп, почему тогда просто не сделать первый экран в xml и все? Без логики,
чтобы еще быстрее начать всем

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/grihabor/garbage-clicker/issues/6#issuecomment-368782456>,
or mute the thread

**Comment by RedSnail** [comment]
Все в работе так или иначе эту стадию пройдут: наличие главной идеи и
отсутствие фич

27 февр. 2018 г. 11:16 ДП пользователь "Gregory" <notifications@github.com>
написал:

**Comment by grihabor** [comment]
Я считаю, что расположения view в xml вполне достаточно, чтобы начать. И вообще, зачем назначать на артема? Если кто-то раньше начнет делать, то пусть делает он

**Comment by grihabor** [comment]
Кажется, задачу стоит закрыть
