### ISSUE TITLE
Каждый должен описать свою версию 

### ISSUE THREAD

**Issue by grihabor** [grihabor/garbage-clicker#8]

**Comment by hailennast** [comment]
Кликая по заводу, ты получаешь деньги "сибурики", за которые ты можешь изменять параметры завода, улучшая его и увеличивая скорость переработки мусора заводом
также за "сибурики" можно увеличивать скорость мусора и улучшать экологию местности

**Comment by DansingWithWolfs** [comment]
Главный игровой экран: на внушительную часть экрана кликабельная мусорка, которая при покупке улучшений приобретает всё более и более человеческий вид (с определенным бафом перерастает даже в перерабатывающий завод).  При каждом нажатии вылетает анимированная цифирка "+ n", где n - текущий прирост сибуриков. На эту валюту покупаются разные апгрейды (на улучшение прироста денег же). Меню апгрейдов - или FragmentLayout, или отдельная активити (что крайне нежелательно, наверное. Хотя гораздо проще для нас, начинающих недокодеров). В качестве экологии можно приплести что-то типа золотых монеток в cookie-clicker'е. На экологию можно купить майн сибуриков, пока пользователь неактивен.
Весь геймплей - тыканье на мусор и покупка апгрейдов, с которыми изменяется внешний вид кликабельно кнопки.

**Comment by JuliaErshova** [comment]
Внешний вид:

1)кнопка в виде мусорки в центре (со временем из ржавого бака она при улучшения становится современным сортировочным заводом)
2) две кнопки снизу: 
⬆️Улучшает мусорку -> увеличивается автоматические производство (покупается за  сибурики)
☝️Улучшает осведомленность населения, увеличивает приток мусора за один клик(покупается за экологию)
3) игровые валюты: 
-Сибурики получаем из автокликов, кликов, образовательной акции
-экология обр.акции, падают иногда и нужен ещё один способ
4)образовательный контент: можно сделать факты про мусор, где человеку нужно выбрать правда ложь, если выигрывает получает экологию и шанс сыграть ещё раз (не более 3 за раз) если проигрывает - небольшой утешительный приз в виде сибуриков
Можно делать такую акцию раз в день или сделать что-то типа куки снитч в печеньке

**Comment by grihabor** [comment]
@JuliaErshova 4 пункт интересный

**Comment by grihabor** [comment]
Всем спасибо, будем тут подсматривать идеи по ходу
