### ISSUE TITLE
сделать систему расчёта мощности клика

### ISSUE THREAD

**Issue by RedSnail** [grihabor/garbage-clicker#90]
делать после #88

**Comment by RedSnail** [comment]
у нас есть улучшение, которое влияет на мощность клика. Сейчас это у нас просто константа, а надо прописать функцию, которая будет рассчитывать его мощность исходя из того, сколько раз это улучшение купили

**Comment by grihabor** [comment]
Что такое мощность клика? Зачем вводить интуитивно непонятное определение?

**Comment by grihabor** [comment]
В общем, этот так входит либо в #107, либо в #74.
